version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres
    networks:
      - pplending
    environment:
      - POSTGRES_USER=pplending
      - POSTGRES_PASSWORD=dfnsi3wj20
      - POSTGRES_DB=pplending
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

networks:
  pplending:
    driver: bridge